name: CI

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master", "ci"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install ToolChain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal

    - name: Install Trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'

    - name: Build
      run: trunk build

    - name: Test
      run: cargo test --verbose --verbose

    - name: Check Format
      run: cargo fmt --all -- --check
      working-directory: src-tauri